name:
  rnamediator
channels:
  - conda-forge
  - defaults
  - bioconda
dependencies:
  - pip
  - pip:
    - biopython
    - pandas
    - natsort
    - sphinx
    - sphinxcontrib-napoleon
    - sphinx-argparse
    - sphinx_rtd_theme
    - pytest-sphinx
    - docutils
    - doc8
    - autodoc
    - mathjax
    - recommonmark
    - configargparse
    - appdirs
